language: java
cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - mvn -P ${CONTAINER} install
after_success:
  - "bash ./.travis-deploy.sh"
matrix:
  include:
    - env: CONTAINER=JBOSS_AS_MANAGED_7.X
      jdk: openjdk7
    - env: CONTAINER=WILDFLY_MANAGED_8
      jdk: oraclejdk8
    - env: CONTAINER=GLASSFISH_MANAGED_3.1
      jdk: openjdk7
    - env: CONTAINER=GLASSFISH_MANAGED_4.0
      jdk: oraclejdk8
    - env: CONTAINER=TOMEE_MANAGED_1.5
      jdk: openjdk7
  allow_failures:
    - env: CONTAINER=TOMEE_MANAGED_1.5
notifications:
  email:
    - "ocpsoft-ci@googlegroups.com"
  irc:
    - "chat.freenode.net#ocpsoft"
env:
  global:
    - secure: "KtSGBCGZ0lhTFvDlD2hPS3G3PalOU+vPZSZ3cFiooCt5NNiPfu7wDlL4874QIlC3T85aBB1AoHBleQl/uDTrYx4pmAYba0hluHQcmfQpvoLXpe/vPpns3AEv5o3/AnPXX3gB8TMldIPcFnS/j5glB7Ur/OYKo10Ae2c2QAD4pR4="
    - secure: "NMIxl5oRmUBP0xxCBe3nEsR8SOckeFtG564Ruaos55FDW6/1OVJ5BjgAuaEFJB8jKv6hRaZYaLsR9axzMm4YPssmC5D9xVdROnS4AnHauTX0+lwENpO9mYnnex7Ol221AOImeYdJvU1SU3JpgTiti7HOIleCciTMdNs2GirBw7s="
